### ISSUE TITLE
Possible legit traffic form Google Translate

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM-Extras#1]
Got this block and it may be legit.

`ID: 1566504152-991450-9517836574
Date/Time: Thu, 22 Aug 2019 14:02:32 -0600
IP Address: 64.233.172.190
Hostname: google-proxy-64-233-172-190.google.com
Query: p=1364
Referrer: https://translate.googleusercontent.com/translate_c?depth=1&amp;hl=it&amp;ie=UTF8&amp;nv=1&amp;prev=_m&amp;rurl=translate.google.it&amp;sl=en&amp;sp=nmt4&amp;tl=it&amp;u=https://www.phpbb.com/community/viewtopic.php%3Ff%3D466%26t%3D2365241&amp;xid=17259,15700022,15700186,15700191,15700256,15700259,15700262,15700265&amp;usg=ALkJrhgHXRtqsmJIDgnaklKwPLmhBVawlw
Signatures Count: 1
Signatures Reference: module_badhosts.php:L273
Why Blocked: Proxy host!
User Agent: Opera/9.80 (Android; Opera Mini/11.0.1912/151.113; U; it) Presto/2.12.423 Version/12.16,gzip(gfe)
Reconstructed URI: https://cyberpcforum.com/viewtopic.php?p=1364`

I thought this was Macmathan's module at first so I opened an issue with him. But he informs me it's yours which I do see now. I asked if perhaps a bypass should be put in place for Google Translate, but Macmathan informs me he was able to view my topic in German so perhaps this connection isn't legit after all? Though, Macmathan informs me that it's due to the Opera browser.

**Comment by Maikuolan** [comment]
Interesting.. Haven't seen this happen before, but definitely worth investigating. I'll play around a bit with it, to see whether I can replicate the problem, and reply back here when I know a little more. :-)

**Comment by Maikuolan** [comment]
*Cross-linking for easy referencing: https://bitbucket.org/macmathan/blocklists/issues/26/possible-legit-traffic-form-google*

**Comment by 737simpilot** [comment]
You may have to test with the Opera App and I'd try the Opera browser as well with Google Translate. I guess I could do this too, but seen as how you're the Dev here and in fact know more than I do, it would be best for you to do the testing. 

I wouldn't keep their crap on your computer or phone though. They are now owned by the Chinese. No offense to the great Chinese people, but their government is in fact communist and straight up sucks.

**Comment by 737simpilot** [comment]
And I see I spelled "from" wrong at Bitbucket...

**Comment by Maikuolan** [comment]
No stress about typos. I literally had to edit *both* of my two earlier replies due to typos. (Well.. technically, I don't *have* to do *anything*.. but if I ignore my own typos, I know I'll probably end up feeling annoyed by them every time I read back over the issues/discussions where they exist and end up seeing them again, so I edit them anyway). Maybe a symptom of thinking faster than I read or type, or.. I don't know. Doesn't really matter, anyway. '^.^

**Comment by 737simpilot** [comment]
You just echoed my same sentiments LOL

**Comment by ghost** [comment]
As I commented over at BitBucket, I think that what we see is the fact that Opera Mini is proxied, and although they are supposed to have a bunch of own proxies it looks by this like they use Google's service for it as well. Maybe things changed since they got Chinese-owned?

The block is not happening due to translation involved, it would have happened on a direct connection as well AFAIK. (https://www.opera.com/mobile/mini/android although they cleverly do not mention the proxy function, read https://en.wikipedia.org/wiki/Opera_Mini for reference)

Just thought I'd mention it here as well.

**Comment by 737simpilot** [comment]
In that case the module did what it was suppose to do. At least in this case it was a new one on me, but the module kicked in never the less. I was just afraid I was blocking Google translation and I certainly didn't want that. 

I ran Opera once just to get a hold of all their ASNs and I blocked them. I didn't want their "VPN" to connect to my site, though I guess that blocks Opera if the use the "VPN" in their browser. When I last tested Opera it was able to be turned off or on I do believe. Many people don't understand VPNs, what they do, etc. Never mid avoiding the Five Eyes jurisdictions, etc. You even have to turn off WebRTC if you are to remain hidden. In a smartphone that's probably a tall order, but in my browser Pale Moon it's off by default. And I poison canvas data and all kinds of crap. 

No, Opera doesn't have a built-in "VPN" it's a damn Chinese government owned proxy. LOL

**Comment by Maikuolan** [comment]
> In that case the module did what it was suppose to do.

Ah, okay.

Haven't quite had time to look into this yet myself (offline commitments), but would it still be worth doing so? Or do we regard this as basically resolved now? (No trouble either way; Just asking to confirm before I proceed, either way).

**Comment by DanielRuf** [comment]
Afaik Opera has a VPN service which is provided from 4 different locations.

**Comment by ghost** [comment]
Not entirely a VPN. Their own head developer once said: 

> In our case we are coming with a new term: a browser VPN – and our goal is that all the network activity from the browser is actually routed via our secure proxy – unlike the usual proxies that only route the web traffic. So it’s different than a system wide VPN but it’s also different than a proxy. Thus – a browser VPN.

Talk about twisting the definitions.

**Comment by ghost** [comment]
Either way, I think the module works as supposed. 
We have the configuration switch for blocking proxies or not. It is a proxy, it got blocked.

**Comment by 737simpilot** [comment]
Looks like the module did what it was supposed to. Closing now.
