### ISSUE TITLE
 Referrer spam module checksum issue

### ISSUE THREAD

**Issue by 737simpilot** [CIDRAM/CIDRAM-Extras#2]
Just updated the module and afterwards CIDRAM said it couldn't activate. I tried repair and couldn't repair. So I uninstalled and went to install again and the checksum is invalid.

**Comment by Maikuolan** [comment]
Looks like a small hiccup occurred due to my trying to update metadata for v2 and v3 modules at the same time; Some wrong wires crossed where they shouldn't have, I guess. Anyway, fixed now. Cheers for noticing this. :-)

**Comment by 737simpilot** [comment]
Wow! That was quick. I was just now going to show the differences in modules.dat. LOL

**Comment by 737simpilot** [comment]
> Looks like a small hiccup occurred due to my trying to update metadata for v2 and v3 modules at the same time; Some wrong wires crossed where they shouldn't have, I guess. Anyway, fixed now. Cheers for noticing this. :-)

No problem. Happens to me all the time. I see your code change and raise you my life! LOL
